volumes:
  arch:

services:
  arch:
    build: .
    container_name: arch
    image: arch
    volumes:
      - /home/user/hack:/root/hack
      - /etc/hosts:/etc/hosts
      - /tmp/.X11-unix:/tmp/.X11-unix #  X11 socket - to access host clipboard
    cap_add:
      - NET_BIND_SERVICE # bind <1024
      - NET_RAW # nmap
      - NET_ADMIN # iptables
      - SYS_ADMIN # to be able to mount
      - DAC_READ_SEARCH # mount (smb)
    #environment:
    #  - DISPLAY=unix$DISPLAY # to access host clipboard
    #  - VULNERS_TOKEN=${VULNERS_TOKEN}
    #  - SHODAN_TOKEN=${SHODAN_TOKEN}
